server:
  port: 8081
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false
  r2dbc:
    url: r2dbc:postgresql://localhost/wallet
    username: postgres
    password: postgres
  application:
    name: wallet-service
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"
  profiles:
      include: null
